---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    tier: wordpress
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: phpmyadmin
          resources:
            requests:
              cpu: "125m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 30
          image: phpmyadmin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: wordpress-mysql.wp-mysql.svc.cluster.local
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
