kind: Kustomization

commonLabels:
  customer: bakery

bases:
- ../../../bases/wordpress/5.7

namespace: bakery

resources:
- namespace.yaml

configMapGenerator:
- name: config-init
  files:
    - config-init/wordpress.mssql
    - config-init/init.sh

patchesStrategicMerge:
- configmap-wordpress.yaml
- deployment-wordpress.yaml

secretGenerator:
- name: wp-pass
  literals:
  - password=Bakery202020
